Fix 'object is not subscriptable' in commons
Resolves the following error
 TypeError: 'Environment' object is not subscriptable

This error was caused by an update in qaseio client, changing the
interface of the Environment object. Now qase-python-commons supports
the new interface.